/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package TCTInterfaces.Utilities;

import TCTInterfaces.Parameters.Interface_Parameters_TermTermRelations;
import TCTInterfaces.Menus.Interface_Menu2;
import TCTIO.SearchIO;
import TCTNetworkGeneration.TermNetworkGeneration;
import TCTNetworkProperties.AverageNumberRelations;
import TCTParameters.Parameters_TermNetwork;
import TCTStructures.Neighbor;
import java.beans.PropertyVetoException;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import weka.core.Instances;
import weka.core.converters.ConverterUtils;

/**
 *
 * @author ragero
 */
public class Interface_Utilities_NetworkProperties_TermTerm extends javax.swing.JInternalFrame {

    private Parameters_TermNetwork parametersSupportNetwork = new Parameters_TermNetwork();
    private Parameters_TermNetwork parametersMutualInformationNetwork = new Parameters_TermNetwork();
    private Parameters_TermNetwork parametersKappaNetwork = new Parameters_TermNetwork();
    private Parameters_TermNetwork parametersShapiroNetwork = new Parameters_TermNetwork();
    private Parameters_TermNetwork parametersYulesQNetwork = new Parameters_TermNetwork();
    
    public Interface_Utilities_NetworkProperties_TermTerm() {
        
        parametersSupportNetwork = new Parameters_TermNetwork();
        parametersMutualInformationNetwork = new Parameters_TermNetwork();
        parametersKappaNetwork = new Parameters_TermNetwork();
        parametersShapiroNetwork = new Parameters_TermNetwork();
        parametersYulesQNetwork = new Parameters_TermNetwork();
        
        initComponents();
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lArff = new javax.swing.JLabel();
        tArff = new javax.swing.JTextField();
        bProcurarArff = new javax.swing.JButton();
        lProb = new javax.swing.JLabel();
        tProb = new javax.swing.JTextField();
        bProcurarProb = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tResults = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        cSupport = new javax.swing.JCheckBox();
        cMutualInf = new javax.swing.JCheckBox();
        cKappa = new javax.swing.JCheckBox();
        cShapiro = new javax.swing.JCheckBox();
        bSupport = new javax.swing.JButton();
        bInfMutua = new javax.swing.JButton();
        bKappa = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        cYuleQ = new javax.swing.JCheckBox();
        jButton5 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Network Properties - Term-Term Relations");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Paths"));

        lArff.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lArff.setText("<html> Document-term matrix (<b>arff with ID</b>): <html>");

        tArff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tArffActionPerformed(evt);
            }
        });

        bProcurarArff.setText("Seach...");
        bProcurarArff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProcurarArffActionPerformed(evt);
            }
        });

        lProb.setText("<html>\nProbability file (<b>term-term relations</b>):\n</html>");

        bProcurarProb.setText("Search...");
        bProcurarProb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProcurarProbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lArff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lProb, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tArff)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bProcurarArff, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tProb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bProcurarProb)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tArff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bProcurarArff))
                    .addComponent(lArff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lProb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tProb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bProcurarProb))
                .addContainerGap())
        );

        jButton1.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jButton1.setText("Analyse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Results"));

        tResults.setColumns(20);
        tResults.setRows(5);
        jScrollPane2.setViewportView(tResults);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Term-Term Relations"));

        cSupport.setText("Support");

        cMutualInf.setText("Mutual Information");

        cKappa.setText("Kappa");

        cShapiro.setText("Piatetsky-Shapiro's");

        bSupport.setText("...");
        bSupport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSupportActionPerformed(evt);
            }
        });

        bInfMutua.setText("...");
        bInfMutua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInfMutuaActionPerformed(evt);
            }
        });

        bKappa.setText("...");
        bKappa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKappaActionPerformed(evt);
            }
        });

        jButton4.setText("...");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        cYuleQ.setText("Yule's Q");

        jButton5.setText("...");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cSupport)
                    .addComponent(cMutualInf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bSupport, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bInfMutua, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(cYuleQ)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(cKappa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bKappa, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addComponent(cShapiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(bSupport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bInfMutua))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cSupport)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cYuleQ)
                                .addComponent(jButton5)
                                .addComponent(cShapiro)
                                .addComponent(jButton4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cKappa)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cMutualInf)
                                .addComponent(bKappa)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tArffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tArffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tArffActionPerformed

    private void bProcurarArffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProcurarArffActionPerformed
        tArff.setText(SearchIO.AbreArq());
    }//GEN-LAST:event_bProcurarArffActionPerformed

    private void bProcurarProbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProcurarProbActionPerformed
        tProb.setText(SearchIO.AbreArq());
    }//GEN-LAST:event_bProcurarProbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        File fileArff = new File(tArff.getText());
        File fileProb = new File(tProb.getText());

        int numTerms = 0;

        if(!fileArff.getAbsolutePath().endsWith(".arff")){
            tResults.setText("Invalid ARF file");
            return;
        }
        if(!fileProb.getAbsolutePath().endsWith(".prb")){
            tResults.setText("Invalid probability file");
            return;
        }
        

        tResults.setText("Loading ARFF file...\n\n");

        Instances dataOriginal = null;
        try{
            ConverterUtils.DataSource trainSource = new ConverterUtils.DataSource(fileArff.getAbsolutePath().toString()); //Carregando arquivo de Dados
            dataOriginal = trainSource.getDataSet();
            numTerms = dataOriginal.numAttributes() - 1;
        }catch(Exception e){
            System.err.println("Error when reading document-term matrix.");
            e.printStackTrace();
            System.exit(0);
        }

        double avgNumber = 0;

        tResults.append("Number of terms: " + (dataOriginal.numAttributes() - 2) + "\n");
        
        if(cSupport.isSelected()){
            tResults.append("Support ------------------- \n");
            if(parametersSupportNetwork.getThresholdNetwork()){
                for(int lim=0;lim<parametersSupportNetwork.getThresholds().size();lim++){
                    double threshold = parametersSupportNetwork.getThreshold(lim);
                    Neighbor[] adjacencyListTerms = TermNetworkGeneration.GenerateSupportNetworkThreshold(fileProb,numTerms,threshold,true);
                    avgNumber = AverageNumberRelations.TermTermNetwork(adjacencyListTerms);
                    tResults.append("- " + threshold + ": " + avgNumber + "\n");
                }    
            }
            if(parametersSupportNetwork.getNetworkTopK()){
                for(int topK=0;topK<parametersSupportNetwork.getKs().size();topK++){
                    int k = parametersSupportNetwork.getK(topK);
                    Neighbor[] adjacencyListTerms = TermNetworkGeneration.GenerateSupportNetworkTopK(fileProb,numTerms,k);
                    avgNumber = AverageNumberRelations.TermTermNetwork(adjacencyListTerms);  
                    tResults.append("- " + k + ": " + avgNumber + "\n");
                }
            }
            
        }
        if(cMutualInf.isSelected()){
            tResults.append("Mutual Information ------------------- \n");
            if(parametersMutualInformationNetwork.getThresholdNetwork()){
                for(int lim=0;lim<parametersMutualInformationNetwork.getThresholds().size();lim++){
                    double threshold = parametersMutualInformationNetwork.getThreshold(lim);
                    Neighbor[] adjacencyListTerms = TermNetworkGeneration.GenerateMutualInformationNetworkThreshold(fileProb,numTerms,threshold,true);
                    avgNumber = AverageNumberRelations.TermTermNetwork(adjacencyListTerms);
                    tResults.append("- " + threshold + ": " + avgNumber + "\n");
                }    
            }
            if(parametersMutualInformationNetwork.getNetworkTopK()){
                for(int topK=0;topK<parametersMutualInformationNetwork.getKs().size();topK++){
                    int k = parametersMutualInformationNetwork.getK(topK);
                    Neighbor[] adjacencyListTerms = TermNetworkGeneration.GenerateMutualInformationNetworkTopK(fileProb,numTerms,k);
                    avgNumber = AverageNumberRelations.TermTermNetwork(adjacencyListTerms);
                    tResults.append("- " + k + ": " + avgNumber + "\n");
                }
            }
        }
        if(cKappa.isSelected()){
            tResults.append("Kappa ------------------- \n");
            if(parametersKappaNetwork.getThresholdNetwork()){
                for(int lim=0;lim<parametersKappaNetwork.getThresholds().size();lim++){
                    double threshold = parametersKappaNetwork.getThreshold(lim);
                    Neighbor[] adjacencyListTerms = TermNetworkGeneration.GenerateKappaNetworkThreshold(fileProb,numTerms,threshold,true);
                    avgNumber = AverageNumberRelations.TermTermNetwork(adjacencyListTerms);
                    tResults.append("- " + threshold + ": " + avgNumber + "\n");
                }    
            }
            if(parametersKappaNetwork.getNetworkTopK()){
                for(int topK=0;topK<parametersKappaNetwork.getKs().size();topK++){
                    int k = parametersKappaNetwork.getK(topK);
                    Neighbor[] adjacencyListTerms = TermNetworkGeneration.GenerateKappaNetworkTopK(fileProb,numTerms,k);
                    avgNumber = AverageNumberRelations.TermTermNetwork(adjacencyListTerms);
                    tResults.append("- " + k + ": " + avgNumber + "\n");
               }
            }    
        }
        if(cShapiro.isSelected()){
            tResults.append("Shapiro ------------------- \n");
            if(parametersShapiroNetwork.getThresholdNetwork()){
                for(int lim=0;lim<parametersShapiroNetwork.getThresholds().size();lim++){
                    double threshold = parametersShapiroNetwork.getThreshold(lim);
                    Neighbor[] adjacencyListTerms = TermNetworkGeneration.GenerateShapiroNetworkThreshold(fileProb,numTerms,threshold,true);
                    avgNumber = AverageNumberRelations.TermTermNetwork(adjacencyListTerms);
                    tResults.append("- " + threshold + ": " + avgNumber + "\n");
                }    
            }
            if(parametersShapiroNetwork.getNetworkTopK()){
                for(int topK=0;topK<parametersShapiroNetwork.getKs().size();topK++){
                    int k = parametersShapiroNetwork.getK(topK);
                    Neighbor[] adjacencyListTerms = TermNetworkGeneration.GenerateShapiroNetworkTopK(fileProb,numTerms,k);
                    avgNumber = AverageNumberRelations.TermTermNetwork(adjacencyListTerms);
                    tResults.append("- " + k + ": " + avgNumber + "\n");
                }
            }    
        }
        if(cYuleQ.isSelected()){
            tResults.append("Shapiro ------------------- \n");
            if(parametersYulesQNetwork.getThresholdNetwork()){
                for(int lim=0;lim<parametersYulesQNetwork.getThresholds().size();lim++){
                    double threshold = parametersYulesQNetwork.getThreshold(lim);
                    Neighbor[] adjacencyListTerms = TermNetworkGeneration.GenerateYulesQNetworkThreshold(fileProb,numTerms,threshold,true);
                    avgNumber = AverageNumberRelations.TermTermNetwork(adjacencyListTerms);
                    tResults.append("- " + threshold + ": " + avgNumber + "\n");
                }       
            }
            if(parametersYulesQNetwork.getNetworkTopK()){
                for(int topK=0;topK<parametersYulesQNetwork.getKs().size();topK++){
                    int k = parametersYulesQNetwork.getK(topK);
                    Neighbor[] adjacencyListTerms = TermNetworkGeneration.GenerateYulesQNetworkTopK(fileProb,numTerms,k);
                    avgNumber = AverageNumberRelations.TermTermNetwork(adjacencyListTerms);
                    tResults.append("- " + k + ": " + avgNumber + "\n");
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bSupportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSupportActionPerformed
        JInternalFrame frame = new Interface_Parameters_TermTermRelations(parametersSupportNetwork, "Support");
        Interface_Menu2.getDesktop().add(frame);
        try {
            frame.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Interface_Menu2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bSupportActionPerformed

    private void bInfMutuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInfMutuaActionPerformed
        JInternalFrame frame = new Interface_Parameters_TermTermRelations(parametersMutualInformationNetwork, "Mutual Information");
        Interface_Menu2.getDesktop().add(frame);
        try {
            frame.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Interface_Menu2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bInfMutuaActionPerformed

    private void bKappaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKappaActionPerformed
        JInternalFrame frame = new Interface_Parameters_TermTermRelations(parametersKappaNetwork, "Kappa");
        Interface_Menu2.getDesktop().add(frame);
        try {
            frame.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Interface_Menu2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bKappaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JInternalFrame frame = new Interface_Parameters_TermTermRelations(parametersShapiroNetwork, "Shapiro");
        Interface_Menu2.getDesktop().add(frame);
        try {
            frame.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Interface_Menu2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JInternalFrame frame = new Interface_Parameters_TermTermRelations(parametersYulesQNetwork, "Yule's Q");
        Interface_Menu2.getDesktop().add(frame);
        try {
            frame.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Interface_Menu2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bInfMutua;
    private javax.swing.JButton bKappa;
    private javax.swing.JButton bProcurarArff;
    private javax.swing.JButton bProcurarProb;
    private javax.swing.JButton bSupport;
    private javax.swing.JCheckBox cKappa;
    private javax.swing.JCheckBox cMutualInf;
    private javax.swing.JCheckBox cShapiro;
    private javax.swing.JCheckBox cSupport;
    private javax.swing.JCheckBox cYuleQ;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lArff;
    private javax.swing.JLabel lProb;
    private javax.swing.JTextField tArff;
    private javax.swing.JTextField tProb;
    private javax.swing.JTextArea tResults;
    // End of variables declaration//GEN-END:variables
}
