//*****************************************************************************
// Author: Rafael Geraldeli Rossi
// E-mail: rgr.rossi at gmail com
// Last-Modified: January 29, 2015
// Description: 
//*****************************************************************************

package TCTInterfaces.Menus;

import TCTConfigurations.SupervisedLearning.SupervisedInductiveConfiguration;
import TCTConfigurations.SupervisedLearning.SupervisedInductiveConfiguration_DocTermAndTermTermRelations;
import TCTConfigurations.SupervisedLearning.SupervisedInductiveConfiguration_EnsembleMultiview;
import TCTConfigurations.SupervisedLearning.SupervisedInductiveConfiguration_FewLabeledExamples;
import TCTConfigurations.SupervisedLearning.SupervisedInductiveConfiguration_TrainTest;
import TCTInterfaces.Classification.Interface_SupervisedInductiveClassification2;
import TCTInterfaces.Classification.Interface_SupervisedInductiveClassification_DocTerm_TermTerm;
import TCTInterfaces.Classification.Interface_SupervisedInductiveClassification_FewLabeledExamples;
import TCTInterfaces.Classification.Interface_SupervisedInductiveClassification_MultiviewEnsemble;
import TCTInterfaces.Classification.Interface_SupervisedInductiveClassification_TrainTest;

/**
 *
 * @author ragero
 */
public class Interface_Menu_SupervisedInductiveClassification extends javax.swing.JFrame {

    SupervisedInductiveConfiguration configurationIndutivo;
    SupervisedInductiveConfiguration_TrainTest configurationIndutivo_TrainTest;
    SupervisedInductiveConfiguration_FewLabeledExamples configurationIndutivoPoucosExemplos;
    SupervisedInductiveConfiguration_DocTermAndTermTermRelations configurationIndutivoDTeTT;
    SupervisedInductiveConfiguration_EnsembleMultiview configurationIndutivoEsembleMultiview;
    
    public Interface_Menu_SupervisedInductiveClassification() {
        configurationIndutivo = new SupervisedInductiveConfiguration();
        configurationIndutivo_TrainTest = new SupervisedInductiveConfiguration_TrainTest();
        configurationIndutivoPoucosExemplos = new SupervisedInductiveConfiguration_FewLabeledExamples();
        configurationIndutivoDTeTT = new SupervisedInductiveConfiguration_DocTermAndTermTermRelations();
        configurationIndutivoEsembleMultiview = new SupervisedInductiveConfiguration_EnsembleMultiview();
        
        initComponents();
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bIndutivo = new javax.swing.JButton();
        bTrainTest = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        bIndutivoPoucosExemplos = new javax.swing.JButton();
        bIndutivaDTeTT1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TCT - Supervised Inductive Classification");
        setResizable(false);

        bIndutivo.setText("<html> <center> X-Fold Cross Validation <br> <font size=\"2\">(Vector Space Model, Doc-Doc Networks,<br> Term-Term Networks, and Doc-Term Networks)</font> </center> <html> ");
        bIndutivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIndutivoActionPerformed(evt);
            }
        });

        bTrainTest.setText("<html> <center> Train-Test Validation <br> <font size=\"2\">(Vector Space Model, Doc-Doc Networks,<br> Term-Term Networks, and Doc-Term Networks)</font> </center> <html> ");
        bTrainTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTrainTestActionPerformed(evt);
            }
        });

        jButton7.setText("<html>\n<center>\nX-Fold Cross Validation <br>\nMultiview Ensemble\n</center>\n</html>");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        bIndutivoPoucosExemplos.setText("<html> <center> Few Labeled Examples <br> <font size = \"2\">(Vector Space Model and Doc-Term Networks)</font> </center> </html>");
        bIndutivoPoucosExemplos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIndutivoPoucosExemplosActionPerformed(evt);
            }
        });

        bIndutivaDTeTT1.setText("<html>\n<center>\nX Fold Cross Validation <br>\n<font size=\"2\">(Networks with Doc-Term and <br>Term-Term Relations)</font>\n</center>\n</html>");
        bIndutivaDTeTT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIndutivaDTeTT1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bIndutivoPoucosExemplos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(bTrainTest, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(bIndutivo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bIndutivaDTeTT1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bIndutivo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bTrainTest, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bIndutivaDTeTT1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bIndutivoPoucosExemplos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new Interface_SupervisedInductiveClassification_MultiviewEnsemble(configurationIndutivoEsembleMultiview);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void bTrainTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTrainTestActionPerformed
        new Interface_SupervisedInductiveClassification_TrainTest(configurationIndutivo_TrainTest);
    }//GEN-LAST:event_bTrainTestActionPerformed

    private void bIndutivoPoucosExemplosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIndutivoPoucosExemplosActionPerformed
        new Interface_SupervisedInductiveClassification_FewLabeledExamples(configurationIndutivoPoucosExemplos);
    }//GEN-LAST:event_bIndutivoPoucosExemplosActionPerformed

    private void bIndutivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIndutivoActionPerformed
        new Interface_SupervisedInductiveClassification2(configurationIndutivo);
    }//GEN-LAST:event_bIndutivoActionPerformed

    private void bIndutivaDTeTT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIndutivaDTeTT1ActionPerformed
        new Interface_SupervisedInductiveClassification_DocTerm_TermTerm(configurationIndutivoDTeTT);
    }//GEN-LAST:event_bIndutivaDTeTT1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bIndutivaDTeTT1;
    private javax.swing.JButton bIndutivo;
    private javax.swing.JButton bIndutivoPoucosExemplos;
    private javax.swing.JButton bTrainTest;
    private javax.swing.JButton jButton7;
    // End of variables declaration//GEN-END:variables
}
